import { FileText, Shield, AlertTriangle, CheckCircle2, Download, Printer, X } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ForensicReportProps {
  data: any;
  onClose: () => void;
}

const ForensicReport = ({ data, onClose }: ForensicReportProps) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-background/80 backdrop-blur-sm p-4 md:p-10 overflow-y-auto">
      <div className="w-full max-w-4xl bg-card rounded-3xl border border-glass shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-300">
        {/* Report Header */}
        <div className="bg-secondary/50 p-6 flex items-center justify-between border-b border-glass sticky top-0 z-10 backdrop-blur-md">
          <div className="flex items-center gap-3">
            <div className="bg-primary/20 p-2 rounded-lg">
              <FileText className="h-6 w-6 text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-bold">REPORT: Automated Forensic Analysis</h2>
              <p className="text-xs text-muted-foreground">Generated by TruthLens AI • {new Date().toLocaleString()}</p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handlePrint} className="hidden md:flex">
              <Printer className="mr-2 h-4 w-4" />
              Print PDF
            </Button>
            <Button variant="ghost" size="icon" onClick={onClose}>
              <X className="h-5 w-5" />
            </Button>
          </div>
        </div>

        <div className="p-8 md:p-12 space-y-12">
          {/* 1. Executive Summary */}
          <section>
            <div className="flex items-center gap-2 mb-4 border-b border-glass pb-2">
              <Shield className="h-5 w-5 text-primary" />
              <h3 className="text-lg font-bold uppercase tracking-wider">1. Executive Summary</h3>
            </div>
            <div className="grid md:grid-cols-3 gap-8 items-start">
              <div className={`col-span-1 rounded-2xl p-6 text-center border ${data.isDeepfake ? 'border-destructive/30 bg-destructive/5' : 'border-success/30 bg-success/5'}`}>
                <p className="text-xs uppercase font-bold text-muted-foreground mb-2">Final Verdict</p>
                <div className="flex flex-col items-center gap-2">
                  {data.isDeepfake ? (
                    <AlertTriangle className="h-10 w-10 text-destructive mb-1" />
                  ) : (
                    <CheckCircle2 className="h-10 w-10 text-success mb-1" />
                  )}
                  <span className={`text-2xl font-black ${data.isDeepfake ? 'text-destructive' : 'text-success'}`}>
                    {data.isDeepfake ? 'FAKE' : 'AUTHENTIC'}
                  </span>
                  <span className="text-sm font-medium">{data.overallConfidence}% Confidence</span>
                </div>
              </div>
              <div className="col-span-2 space-y-4">
                <p className="text-lg leading-relaxed text-foreground">
                  {data.executiveSummary}
                </p>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div className="bg-secondary/30 p-3 rounded-xl border border-glass">
                    <span className="text-muted-foreground block text-[10px] uppercase font-bold">Detection Engine</span>
                    <span className="font-semibold">{data.detectionEngine}</span>
                  </div>
                  <div className="bg-secondary/30 p-3 rounded-xl border border-glass">
                    <span className="text-muted-foreground block text-[10px] uppercase font-bold">Explanation Engine</span>
                    <span className="font-semibold">{data.explanationEngine}</span>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* 2. Technical Findings */}
          <section>
            <div className="flex items-center gap-2 mb-6 border-b border-glass pb-2">
              <FileText className="h-5 w-5 text-primary" />
              <h3 className="text-lg font-bold uppercase tracking-wider">2. Technical Findings</h3>
            </div>
            <div className="space-y-6">
              {data.anomalies.map((anomaly: any, idx: number) => (
                <div key={idx} className="bg-secondary/20 rounded-2xl p-6 border border-glass">
                  <div className="flex justify-between items-start mb-4">
                    <div>
                      <span className="text-xs font-bold text-primary uppercase tracking-widest">{anomaly.type}</span>
                      <h4 className="text-xl font-bold mt-1">{anomaly.region}</h4>
                    </div>
                    <div className="bg-background/50 px-3 py-1 rounded-full text-xs font-mono">
                      Timestamp: {anomaly.timestamp}s
                    </div>
                  </div>
                  <p className="text-muted-foreground leading-relaxed italic border-l-2 border-primary/30 pl-4">
                    {anomaly.description}
                  </p>
                </div>
              ))}
            </div>
          </section>

          {/* 3. Methodology */}
          <section>
            <div className="flex items-center gap-2 mb-4 border-b border-glass pb-2">
              <Shield className="h-5 w-5 text-primary" />
              <h3 className="text-lg font-bold uppercase tracking-wider">3. Methodology</h3>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              {data.reportData.methodology}
            </p>
            <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4">
               {Object.entries(data.technicalDetails).map(([key, value]) => (
                 <div key={key} className="bg-background/40 p-3 rounded-lg border border-glass/50">
                    <span className="text-[10px] text-muted-foreground uppercase block mb-1">{key.replace(/([A-Z])/g, ' $1')}</span>
                    <span className="text-sm font-semibold">{value as string}</span>
                 </div>
               ))}
            </div>
          </section>

          {/* 4. Recommendations */}
          <section className="bg-primary/5 rounded-3xl p-8 border border-primary/20">
            <h3 className="text-lg font-bold uppercase tracking-wider mb-6 flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-primary" />
              4. Recommendations
            </h3>
            <ul className="grid gap-4 md:grid-cols-3">
              {data.reportData.recommendations.map((rec: string, i: number) => (
                <li key={i} className="flex gap-3 text-sm">
                  <div className="h-5 w-5 rounded-full bg-primary/20 flex items-center justify-center text-primary font-bold shrink-0">{i+1}</div>
                  <p className="text-muted-foreground">{rec}</p>
                </li>
              ))}
            </ul>
          </section>
        </div>

        <div className="bg-secondary/50 p-8 text-center border-t border-glass">
          <p className="text-xs text-muted-foreground mb-4">
            CONFIDENTIAL: This report is for informational purposes only. TruthLens AI does not guarantee 100% accuracy in identifying all forms of media manipulation.
          </p>
          <div className="flex justify-center gap-4">
             <Button className="bg-gradient-primary">
                <Download className="mr-2 h-4 w-4" /> Download PDF Report
             </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ForensicReport;
